[package]
name = "wiretun"
description = "WireGuard Library"
version = "0.0.0"
authors = ["lodrem <jialun.cai@pm.me>"]
keywords = ["wireguard"]
repository = "https://github.com/lodrem/wiretun"
homepage = "https://github.com/lodrem/wiretun"
documentation = "https://docs.rs/wiretun"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
